### ISSUE TITLE
开启两步验证后，官网无法登陆

### ISSUE THREAD

**Issue by se4** [qbtrade/onetoken#1]
开发者大大您好：

清理cookies后重新登陆1token.trade，提示需要两步验证，但是并没有地方输入我的谷歌验证码。
接口应该没问题，是前端页面没有加入输入框吧。

> api/v1/user/login
> {"username":"xxx","password":"xxx","verification_code":{"type":"_goole_","**code**":""}}

然后google写成goole是有意为之还是....

**Comment by ZTjack** [comment]
@se4 感谢热心小伙伴的测试，咳咳。。。就是因为goole这个问题。。写这个bug的程序员已祭天，请放心
推荐您加入我们的微信群，有问题直接在群里问就行。
然后请留一下你的微信号，我加一下你~~~~

**Comment by se4** [comment]
@ZTjack 请您查收邮箱，上头有二维码！

**Comment by ZTjack** [comment]
@se4 额，麻烦再发一次，我邮箱查过了，没有收到您的邮件，麻烦啦~~~~~

**Comment by se4** [comment]
@ZTjack geekcorn
